### PR TITLE
Demo Functionality

### PR DESCRIPTION
**Pull request by damithdev**
+Common mobile view flag
+Expandable row flag
+Demo Table Pagination
+Demo Sort
+Demo Simple Search Functionality

### CODE REVIEW

**Comment by maurobotta** [comment]
Great!

Thank you @damithdev

**Comment by maurobotta** [comment]
> +Common mobile view flag
> +Expandable row flag
> +Demo Table Pagination
> +Demo Sort
> +Demo Simple Search Functionality

Hi @damithdev 

Do you have others fix or new features for demo project?

**Comment by damithdev** [comment]
> > +Common mobile view flag
> > +Expandable row flag
> > +Demo Table Pagination
> > +Demo Sort
> > +Demo Simple Search Functionality
> 
> Hi @damithdev 
> 
> Do you have others fix or new features for demo project?

@maurobotta ,

I think this is pretty much all. Do you have any suggestions?

**Comment by maurobotta** [comment]
@damithdev

- Keyboard support
-  Better row selection / focused


- Add custom color font title:


Text("${header.text}",
textAlign: header.textAlign,

>>>        style: TextStyle(color: Colors.blue)),

if (widget.sortColumn != null && widget.sortColumn == header.value)
widget.sortAscending ? Icon(Icons.arrow_downward, size: 15) : Icon(Icons.arrow_upward, size: 15)         ],

**Pull request merged**
